DEFAULT_MODEL = "CompVis/stable-diffusion-v1-4"
DEFAULT_SPLIT = "train"
DEFAULT_IMAGE_COLUMN = "1600px"
DEFAULT_TEXT_COLUMN = "info_alt"
DEFAULT_RESOLUTION = 384
DEFAULT_FILL = 255
DEFAULT_BATCH_SIZE = 2
DEFAULT_LR = 1e-6

DEFAULT_FINETUNED_UNET = "gloriadrm/finetuned-oldbook-unet"
DEFAULT_OUTPUT_DIR = "../outputs"
DEFAULT_STEPS = 30
DEFAULT_GUIDANCE_SCALE = 7.5
DEFAULT_SEED = 42